FROM ubuntu:24.04
RUN apt-get update && apt-get install -y --no-install-recommends \
    python3.12 python3.12-venv python3-pip \
    && rm -rf /var/lib/apt/lists/* \
    && groupadd -r appgroup && useradd -r -g appgroup appuser
WORKDIR /app
COPY . /app
USER appuser
EXPOSE 80 443
#CMD ["python3", "app.py"] 
